### ISSUE TITLE
Better tutorial/data

### ISSUE THREAD

**Issue by lskatz** [genotoul-bioinfo/Binette#19]
Hi, this is coming off of #18 and as a comment on the review for JOSS <https://github.com/openjournals/joss-reviews/issues/6782>.

* Please include real data in the repo in one way or another
* Please include a tutorial on how to use real data so that a user can follow it from beginning to end. One real datum that you could use is the one in #18 or maybe something from the CAMI benchmark datasets.
* Hook the real data into GitHub Actions even if it's in a minor way

**Comment by JeanMainguy** [comment]
Hi,

I agree that would be important to provide a clear tutorial on how to use Binette with real data. I'll look into the best ways to include this in the repository. I'll probably add a new section in the documentation.

However, for GitHub Actions, I think we should stick to basic examples that demonstrate the full process without the size of real data. The main goal of the GitHub CI pipeline is to run tests when code changes, ensuring everything works as expected. Since these tests might run often, it's best to keep them quick to minimize computing time. So, I think the current [test dataset](https://github.com/genotoul-bioinfo/Binette_TestData) fulfills this purpose well.

**Comment by lskatz** [comment]
Understood! I will strike the suggestion for using real data in github actions, but I would appreciate a clear tutorial using real data.

**Comment by JeanMainguy** [comment]
Hi,

The tutorial is now live! You can check it out here: https://binette.readthedocs.io/en/latest/tutorial/tutorial_main.html.

I’ve used the data you suggested from the ncezid-biome/datasets. 

Also, I've released a new minor version that includes a new feature: it now generates quality reports for the input bins. Since the quality assessment is already part of the process, these new reports make it easier to compare the original input bins with the results produced by Binette.
