### ISSUE TITLE
(Question/feature request) - is there support for precomputed genes? If not, can this be added?

### ISSUE THREAD

**Issue by jolespin** [genotoul-bioinfo/Binette#30]
I’m working on reimplementing my https://github.com/jolespin/veba metagenomics software suite and was looking into lightweight alternatives to das tool.  I already precompute the genes with pyrodigal in an earlier step and I’m working on reducing all redundancies in my workflow.  Is it possible to provide precomputed genes to your workflow? CheckM2 already supports precomputed genes which is how I currently use it.

**Comment by JeanMainguy** [comment]
Hi Josh,

Thanks for reaching out! Currently, it’s not possible to provide precomputed genes to Binette, but this is definitely something that could be implemented. It would make a lot of sense, especially since gene calling is usually done separately in most cases.

The main challenge would be mapping the genes back to their contigs. I think one simple solution could be to assume that gene IDs follow Pyrodigal’s naming convention: `<contigID>_<GeneID>`. In this case, the user would only need to provide a single protein FASTA file with all the predicted proteins for the assembly.

Alternatively, we could also add support for a mapping file that explicitly links gene IDs to contig IDs. This approach wouldn’t require specific naming conventions, but it would involve a bit more setup on the user’s end.

Let me know what you think of these options.

**Comment by jolespin** [comment]
Yea of course! I'm very excited about your package as I've been looking for a lightweight tool I can add to my workflows since DAS Tool has a lot of very specific dependencies. 

 > The main challenge would be mapping the genes back to their contigs. I think one simple solution could be to assume that gene IDs follow Pyrodigal’s naming convention: <contigID>_<GeneID>. In this case, the user would only need to provide a single protein FASTA file with all the predicted proteins for the assembly.
> Alternatively, we could also add support for a mapping file that explicitly links gene IDs to contig IDs. This approach wouldn’t require specific naming conventions, but it would involve a bit more setup on the user’s end.

I was trying to think of all the possibilities and I've thought of a couple: 
1. As you mentioned, assume that the user ran Pyrodigal or similar (e.g., Pyrodigal-GV) for their gene calls and the contig ID can be parser from the gene ID.  This would by far be the easiest and I think this is what is already done in DAS Tool.  The only downside is that it would only be able to be used by users who are using Prodigal-based gene calls (which is a fair assumption b/c most people do). 
2. Include a manifest file that has [id_genome] [path/to/genome.fasta] [path/to/proteins.fasta] [path/to/genome.gff] which would be the most flexible along with an argument that has the gene attribute (e.g., should it look for ID, gene_id, locus_tag, etc).  The GFF file will have which contig the gene came from and most people should have this already. If you're expecting a specific directory structure like one you use w/ your workflow you can make a helper script that comes w/ your package.  I have one here that I use: https://github.com/jolespin/veba/blob/main/bin/scripts/compile_genomes_table.py
3. Another alternative is to provide the files above manually and assume the genome ID is in the base name [e.g., bin1.fa, bin1.faa, bin1.gff].

**Comment by JeanMainguy** [comment]
Thanks for sharing your thoughts on how to implement this feature!

What Binette does is first perform gene calling with Pyrodigal on all contigs and then run the DIAMOND step of CheckM2 on all genes. From the DIAMOND results, Binette can estimate contamination and completeness for any combination of contigs.

If users provide precomputed genes, this allows skipping the Pyrodigal step, which is great ! However, since gene calling is done once for all contigs, there’s no need to split the genes by bins. Single GFF/FASTA files containing all the genes for all contigs would be sufficient and much simpler for the user. 

I’d prefer not to rely on GFF files for mapping genes to their contigs. As you said genes IDs can be found in multiple attributes in GFF files (ID, gene_id, locus_tag, etc.), which make the mapping less straightforward. Using an additional argument to explicitly specify which attribute contains the IDs could work though.

As you mentioned, the simplest solution would be to assume that gene IDs follow Pyrodigal’s naming scheme. If there’s a real need in the future, we could consider adding support for more flexible mappings using a GFF file for example.

**Comment by JeanMainguy** [comment]
I think I can implement this change quickly and release a new version soon.

**Comment by jolespin** [comment]
That's great news. You're totally right in that in wouldn't make sense to have the bins all partitioned for the GFF and protein files (totally defeats the purpose haha).  Sorry about that suggestion was kind of on autopilot yesterday jumping between tasks.  VEBA does the same thing in tuning pyrodigal once in the beginning on the entire assembly, then bins, then partitions out the gene models.  Decreases the overhead quite a bit (though some of the backend binners use fraggenescan anyways but I'm trying to phase these out).  The prodigal assumption would definitely be the lowest hanging fruit to get this operational.

**Comment by JeanMainguy** [comment]
I implemented the feature in the `dev` branch, if you want to give a go. You can provide the genes fasta file with `--proteins`.

I'll release a new version very soon.

**Comment by JeanMainguy** [comment]
A new version has been released: [v1.0.4](https://github.com/genotoul-bioinfo/Binette/releases/tag/v1.0.4)!  
It will be available on Bioconda shortly. 

Thanks for the suggestion !

**Comment by jolespin** [comment]
Can't wait to give it a shot next week. Thanks again for hopping on this so quickly.
